[package]
name = "rust-roguelike"
version = "0.1.0"
authors = ["bundai223 <bundai223@gmail.com>"]
#[dependencies]
#tcod = "0.8.0"
[dependencies.tcod]
git = "https://github.com/tomassedovic/tcod-rs.git"
rev = "8934fbf0d04826fd9dcc74a7e071c36f3bd15fef" #v0.8
